---
server:
    port: 8090
    contextPath: /base

---
grails:
    profile: rest-api
    codegen:
        defaultPackage: bizhare.base
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 5000000
            maxRequestSize: 5000000
    converters:
        encoding: UTF-8
    web:
        servlet:
            path: /*

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

environments:
    development:
        server:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/db
            driverClassName: org.postgresql.Driver
            username: postgres
            password: password
    test:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/db
            driverClassName: org.postgresql.Driver
            username: postgres
            password: password
    production:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/db
            driverClassName: org.postgresql.Driver
            username: postgres
            password: password
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
